### ISSUE TITLE
Empty network selected as best fitting network. 

### ISSUE THREAD

**Issue by sarahkertz** [SachaEpskamp/bootnet#10]
I get this message when I try to use the case dropping bootstrapping method (using this command: bootcent<-bootnet(Network2, gamma = .5, nBoots = 1000, type = "case")

"An empty network was selected to be the best fitting network. Possibly set 'lambda.min.ratio' higher to search more sparse networks. You can also change the 'gamma' parameter to improve sensitivity (at the cost of specificity)."

I've changed gamma around but no difference. I can't find any information on changing the lambda.min.ratio option. Any thoughts much appreciated.

**Comment by SachaEpskamp** [comment]
This is a qgraph message indicating the sparsest network was selected. It is not necessarily a problem, especially if you didn't get it in your original analysis. You could try changing the gamma parameter by using the bootnet argument 'tuning'. e.g.,
`
estimateNetwork(..., tuning = 0)
`
to perform BIC selection instead of EBIC selection.
