### ISSUE TITLE
Error with Bootnet's default = c("cor", "TMFG")

### ISSUE THREAD

**Issue by lindoyle** [SachaEpskamp/bootnet#12]
I would like to run the following code (which I believe should be possible from your most recent updates of the bootnet package)
```
netSimulator(input = genGGM(NVar = 40),
  nCases = c(50, 100, 250, 500, 1000, 2500),
  nReps = 10, # for testing code
  default = c("cor", "TMFG"))
```
But I get the following error: 
```
Error in netSimulator(input = genGGM(NVar = 40), nCases = c(50, 100, 250,  : 
  Default set 'cor' not yet supported. Please manually specify 'dataGenerator'Default set 'EBICglasso' not yet supported. Please manually specify 'dataGenerator'Default set 'TMFG' not yet supported. Please manually specify 'dataGenerator'
```
Any help would be greatly appreciated.

**Comment by SachaEpskamp** [comment]
The problem is that netSimulator does not know what model to use in data generation (if you use default = "EBICglasso" it knows to generate a GGM). It should work with adding the argument `dataGenerator = ggmGenerator`. Note though that correlation networks do not aim to estimate a GGM and will likely show poor performance.

**Comment by lindoyle** [comment]
Thank you for your reply.
Running this still yields an error message and a lot of warnings:  
```
netSimulator(
  input = genGGM(Nvar = 40),
  nCases = c(50, 100, 250, 500, 1000, 2500),
  nReps = 10, 
  default = c("cor", "TMFG"), 
  dataGenerator = ggmGenerator)
```
```
Error in match.arg(default) : 
  'arg' should be one of “none”, “EBICglasso”, “pcor”, “IsingFit”, “IsingSampler”, “huge”, “adalasso”, “mgm”, “relimp”
```
Any suggestions?

**Comment by mjbsp** [comment]
[ggmGenerator](https://www.rdocumentation.org/packages/bootnet/versions/1.0.1/topics/ggmGenerator) is a function. If you add () after it, it will use the default settings for the function, ie. (ordinal = FALSE, nLevels = 4). You can also adjust those values so that it better approximates the data you are interested in.

E.g., this will work

```
netSimulator(
  input = genGGM(Nvar = 40),
  nCases = c(50, 100, 250, 500, 1000, 2500),
  nReps = 10, 
  default = c("cor", "TMFG"), 
  dataGenerator = ggmGenerator())
```

And this will make the data ordinal

```
netSimulator(
  input = genGGM(Nvar = 40),
  nCases = c(50, 100, 250, 500, 1000, 2500),
  nReps = 10, 
  default = c("cor", "TMFG"), 
  dataGenerator = ggmGenerator(ordinal = T))
```

**Comment by mjbsp** [comment]
[ggmGenerator](https://www.rdocumentation.org/packages/bootnet/versions/1.0.1/topics/ggmGenerator) is a function. If you add () after it, it will use the default settings for the function, ie. (ordinal = FALSE, nLevels = 4). You can also adjust those values so that it better approximates the data you are interested in.

E.g., this will work

```
netSimulator(
  input = genGGM(Nvar = 40),
  nCases = c(50, 100, 250, 500, 1000, 2500),
  nReps = 10, 
  default = c("cor", "TMFG"), 
  dataGenerator = ggmGenerator())
```

And this will make the data ordinal

```
netSimulator(
  input = genGGM(Nvar = 40),
  nCases = c(50, 100, 250, 500, 1000, 2500),
  nReps = 10, 
  default = c("cor", "TMFG"), 
  dataGenerator = ggmGenerator(ordinal = T))
```
